name: Firebase Database Status Check

on:
  schedule:
    - cron: "0 * * * *" # Run every hour (0th minute of every hour)

jobs:
  check-database-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Firebase script
        run: npx ts-node -r tsconfig-paths/register ./app/api/statusTracker/route.ts
